#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

# -----------------------------
# Common
# -----------------------------
DATASET="${DATASET:-cwq}"
MODEL_IMPL="${MODEL_IMPL:-trm_hier6}"
EMB_MODEL="${EMB_MODEL:-intfloat/multilingual-e5-large}"
EMB_TAG="${EMB_TAG:-$(echo "$EMB_MODEL" | tr '/:' '__' | tr -cd '[:alnum:]_.-')}"
EMB_DIR="${EMB_DIR:-trm_agent/emb/${DATASET}_${EMB_TAG}}"
CKPT_DIR="${CKPT_DIR:-trm_agent/ckpt/${DATASET}_${MODEL_IMPL}_subgraph_r16_h768_schedcos_scratch}"
FT_CKPT_DIR="${FT_CKPT_DIR:-${CKPT_DIR}_hardloss_ft}"

# -----------------------------
# Step1: ckpt select (ep range)
# -----------------------------
EP_START="${EP_START:-20}"
EP_END="${EP_END:-28}"
SELECT_EVAL_LIMIT="${SELECT_EVAL_LIMIT:--1}"
SELECT_BATCH_SIZE="${SELECT_BATCH_SIZE:-8}"
GAP_TOL="${GAP_TOL:-0.01}"

SUBGRAPH_HOPS="${SUBGRAPH_HOPS:-3}"
SUBGRAPH_MAX_NODES="${SUBGRAPH_MAX_NODES:-2048}"
SUBGRAPH_MAX_EDGES="${SUBGRAPH_MAX_EDGES:-8192}"
SUBGRAPH_PRED_THRESHOLD="${SUBGRAPH_PRED_THRESHOLD:-0.5}"
SUBGRAPH_SPLIT_REVERSE_RELATIONS="${SUBGRAPH_SPLIT_REVERSE_RELATIONS:-false}"
SUBGRAPH_DIRECTION_EMBEDDING_ENABLED="${SUBGRAPH_DIRECTION_EMBEDDING_ENABLED:-false}"
DEV_USES_TEST_SPLIT="${DEV_USES_TEST_SPLIT:-false}"
TEST_ONLY_EVAL="${TEST_ONLY_EVAL:-false}"
SELECT_MODE="${SELECT_MODE:-gap_then_test_hit}"

# -----------------------------
# Step2: hard-loss fine-tune
# -----------------------------
FT_EPOCHS="${FT_EPOCHS:-10}"
FT_LR="${FT_LR:-1e-6}"
FT_BATCH_SIZE="${FT_BATCH_SIZE:-1}"
FT_EVAL_LIMIT="${FT_EVAL_LIMIT:--1}"

FT_SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED="${FT_SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED:-true}"
FT_SUBGRAPH_BCE_HARD_NEGATIVE_TOPK="${FT_SUBGRAPH_BCE_HARD_NEGATIVE_TOPK:-64}"
FT_SUBGRAPH_RANKING_ENABLED="${FT_SUBGRAPH_RANKING_ENABLED:-true}"
FT_SUBGRAPH_RANKING_WEIGHT="${FT_SUBGRAPH_RANKING_WEIGHT:-0.1}"
FT_SUBGRAPH_RANKING_MARGIN="${FT_SUBGRAPH_RANKING_MARGIN:-0.5}"
FT_SUBGRAPH_HARD_NEGATIVE_TOPK="${FT_SUBGRAPH_HARD_NEGATIVE_TOPK:-16}"
FT_SUBGRAPH_LR_SCHEDULER="${FT_SUBGRAPH_LR_SCHEDULER:-none}"
TRAIN_EVAL_SPLIT="${TRAIN_EVAL_SPLIT:-dev}"  # dev|test
AUTO_TEST_AFTER_TRAIN="${AUTO_TEST_AFTER_TRAIN:-true}"

# -----------------------------
# Distributed / wandb
# -----------------------------
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3}"
NPROC_PER_NODE="${NPROC_PER_NODE:-4}"
MASTER_PORT="${MASTER_PORT:-29612}"
DDP_TIMEOUT_MINUTES="${DDP_TIMEOUT_MINUTES:-180}"
PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
SELECT_TEST_NPROC_PER_NODE="${SELECT_TEST_NPROC_PER_NODE:-$NPROC_PER_NODE}"
SELECT_TEST_MASTER_PORT_BASE="${SELECT_TEST_MASTER_PORT_BASE:-29640}"

WANDB_MODE="${WANDB_MODE:-online}"
WANDB_PROJECT="${WANDB_PROJECT:-graph-traverse}"
WANDB_ENTITY="${WANDB_ENTITY:-}"
WANDB_RUN_NAME="${WANDB_RUN_NAME:-cwq_fine_tune}"

OUT_DIR="${OUT_DIR:-logs}"
BEST_ENV="${BEST_ENV:-$OUT_DIR/best_ckpt_ep${EP_START}_${EP_END}.env}"

# Use first visible GPU for step1 single-GPU eval.
FIRST_VISIBLE_GPU="$(echo "$CUDA_VISIBLE_DEVICES" | cut -d',' -f1)"
SELECT_CUDA_DEVICE="${SELECT_CUDA_DEVICE:-$FIRST_VISIBLE_GPU}"

mkdir -p "$OUT_DIR"

echo "[pipeline] step1: select best ckpt (dev/test gap + test hit)"
DATASET="$DATASET" \
MODEL_IMPL="$MODEL_IMPL" \
EMB_MODEL="$EMB_MODEL" \
EMB_TAG="$EMB_TAG" \
EMB_DIR="$EMB_DIR" \
CKPT_DIR="$CKPT_DIR" \
EP_START="$EP_START" \
EP_END="$EP_END" \
EVAL_LIMIT="$SELECT_EVAL_LIMIT" \
BATCH_SIZE="$SELECT_BATCH_SIZE" \
CUDA_DEVICE="$SELECT_CUDA_DEVICE" \
GAP_TOL="$GAP_TOL" \
SUBGRAPH_HOPS="$SUBGRAPH_HOPS" \
SUBGRAPH_MAX_NODES="$SUBGRAPH_MAX_NODES" \
SUBGRAPH_MAX_EDGES="$SUBGRAPH_MAX_EDGES" \
SUBGRAPH_PRED_THRESHOLD="$SUBGRAPH_PRED_THRESHOLD" \
SUBGRAPH_SPLIT_REVERSE_RELATIONS="$SUBGRAPH_SPLIT_REVERSE_RELATIONS" \
SUBGRAPH_DIRECTION_EMBEDDING_ENABLED="$SUBGRAPH_DIRECTION_EMBEDDING_ENABLED" \
DEV_USES_TEST_SPLIT="$DEV_USES_TEST_SPLIT" \
TEST_ONLY_EVAL="$TEST_ONLY_EVAL" \
SELECT_MODE="$SELECT_MODE" \
TEST_NPROC_PER_NODE="$SELECT_TEST_NPROC_PER_NODE" \
TEST_MASTER_PORT_BASE="$SELECT_TEST_MASTER_PORT_BASE" \
OUT_DIR="$OUT_DIR" \
BEST_ENV="$BEST_ENV" \
bash trm_rag_style/scripts/run_select_subgraph_ckpt_devtest_gap.sh

if [ ! -f "$BEST_ENV" ]; then
  echo "[err] best env not found: $BEST_ENV"
  exit 2
fi

# shellcheck source=/dev/null
source "$BEST_ENV"
if [ -z "${BEST_CKPT:-}" ]; then
  echo "[err] BEST_CKPT is empty in $BEST_ENV"
  exit 2
fi

echo "[pipeline] selected: BEST_EP=${BEST_EP:-?} BEST_CKPT=${BEST_CKPT}"
echo "[pipeline] step2: hard-loss fine-tune on 4 GPUs (wandb=${WANDB_MODE}, run=${WANDB_RUN_NAME})"
echo "[pipeline] fine-tune ckpt_dir: $FT_CKPT_DIR"

CUDA_VISIBLE_DEVICES="$CUDA_VISIBLE_DEVICES" \
NPROC_PER_NODE="$NPROC_PER_NODE" \
MASTER_PORT="$MASTER_PORT" \
DDP_TIMEOUT_MINUTES="$DDP_TIMEOUT_MINUTES" \
PYTORCH_CUDA_ALLOC_CONF="$PYTORCH_CUDA_ALLOC_CONF" \
BEST_ENV="$BEST_ENV" \
CKPT="$BEST_CKPT" \
DATASET="$DATASET" \
MODEL_IMPL="$MODEL_IMPL" \
EMB_MODEL="$EMB_MODEL" \
EMB_TAG="$EMB_TAG" \
EMB_DIR="$EMB_DIR" \
CKPT_DIR="$FT_CKPT_DIR" \
EPOCHS="$FT_EPOCHS" \
BATCH_SIZE="$FT_BATCH_SIZE" \
LR="$FT_LR" \
EVAL_LIMIT="$FT_EVAL_LIMIT" \
SUBGRAPH_HOPS="$SUBGRAPH_HOPS" \
SUBGRAPH_MAX_NODES="$SUBGRAPH_MAX_NODES" \
SUBGRAPH_MAX_EDGES="$SUBGRAPH_MAX_EDGES" \
SUBGRAPH_SPLIT_REVERSE_RELATIONS="$SUBGRAPH_SPLIT_REVERSE_RELATIONS" \
SUBGRAPH_DIRECTION_EMBEDDING_ENABLED="$SUBGRAPH_DIRECTION_EMBEDDING_ENABLED" \
SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED="$FT_SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED" \
SUBGRAPH_BCE_HARD_NEGATIVE_TOPK="$FT_SUBGRAPH_BCE_HARD_NEGATIVE_TOPK" \
SUBGRAPH_RANKING_ENABLED="$FT_SUBGRAPH_RANKING_ENABLED" \
SUBGRAPH_RANKING_WEIGHT="$FT_SUBGRAPH_RANKING_WEIGHT" \
SUBGRAPH_RANKING_MARGIN="$FT_SUBGRAPH_RANKING_MARGIN" \
SUBGRAPH_HARD_NEGATIVE_TOPK="$FT_SUBGRAPH_HARD_NEGATIVE_TOPK" \
SUBGRAPH_LR_SCHEDULER="$FT_SUBGRAPH_LR_SCHEDULER" \
TRAIN_EVAL_SPLIT="$TRAIN_EVAL_SPLIT" \
AUTO_TEST_AFTER_TRAIN="$AUTO_TEST_AFTER_TRAIN" \
WANDB_MODE="$WANDB_MODE" \
WANDB_PROJECT="$WANDB_PROJECT" \
WANDB_ENTITY="$WANDB_ENTITY" \
WANDB_RUN_NAME="$WANDB_RUN_NAME" \
bash trm_rag_style/scripts/run_train_subgraph_hardloss_resume.sh

echo "[done] select+finetune pipeline completed"
