#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

RUN_TAG="${RUN_TAG:-$(date +%Y%m%d_%H%M%S)}"

# E experiment: ReaRev + latent + TRM-style hybrid on GPU 2,3
CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-2,3}" \
NPROC_PER_NODE="${NPROC_PER_NODE:-2}" \
MASTER_PORT="${MASTER_PORT:-29688}" \
WANDB_ANONYMOUS="${WANDB_ANONYMOUS:-allow}" \
WANDB_MODE="${WANDB_MODE:-online}" \
WANDB_PROJECT="${WANDB_PROJECT:-graph-traverse}" \
WANDB_RUN_NAME="${WANDB_RUN_NAME:-cwq-rearev-E-gpu23-kltrm-${RUN_TAG}}" \
CKPT_DIR="${CKPT_DIR:-trm_agent/ckpt/cwq_trm_hier6_rearev_E_gpu23_kltrm_${RUN_TAG}}" \
EPOCHS="${EPOCHS:-16}" \
BATCH_SIZE="${BATCH_SIZE:-2}" \
LR="${LR:-2e-4}" \
SUBGRAPH_RECURSION_STEPS="${SUBGRAPH_RECURSION_STEPS:-4}" \
SUBGRAPH_REAREV_ADAPT_STAGES="${SUBGRAPH_REAREV_ADAPT_STAGES:-2}" \
SUBGRAPH_GRAD_ACCUM_STEPS="${SUBGRAPH_GRAD_ACCUM_STEPS:-4}" \
SUBGRAPH_MAX_NODES="${SUBGRAPH_MAX_NODES:-2048}" \
SUBGRAPH_MAX_EDGES="${SUBGRAPH_MAX_EDGES:-8192}" \
SUBGRAPH_LOSS_MODE="${SUBGRAPH_LOSS_MODE:-rearev_kl_trm}" \
SUBGRAPH_REAREV_TRM_WEIGHT="${SUBGRAPH_REAREV_TRM_WEIGHT:-0.2}" \
SUBGRAPH_REAREV_TRM_CE_WEIGHT="${SUBGRAPH_REAREV_TRM_CE_WEIGHT:-1.0}" \
SUBGRAPH_REAREV_TRM_HALT_BCE_WEIGHT="${SUBGRAPH_REAREV_TRM_HALT_BCE_WEIGHT:-1.0}" \
SUBGRAPH_DDP_FIND_UNUSED_PARAMETERS="${SUBGRAPH_DDP_FIND_UNUSED_PARAMETERS:-true}" \
SUBGRAPH_REAREV_TRM_STYLE_ENABLED="${SUBGRAPH_REAREV_TRM_STYLE_ENABLED:-true}" \
SUBGRAPH_REAREV_TRM_TMINUS1_NO_GRAD="${SUBGRAPH_REAREV_TRM_TMINUS1_NO_GRAD:-true}" \
SUBGRAPH_REAREV_TRM_DETACH_CARRY="${SUBGRAPH_REAREV_TRM_DETACH_CARRY:-true}" \
bash trm_rag_style/scripts/run_rearev_trm_isolated.sh
