#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

# Load frozen "current method" defaults (user env still overrides).
# shellcheck source=/dev/null
source "$REPO_ROOT/trm_rag_style/configs/subgraph_method_current_hardloss.env"

echo "[method] current_snapshot=hardloss"
echo "[method] dataset=$DATASET model=$MODEL_IMPL emb_tag=$EMB_TAG"
echo "[method] hops=$SUBGRAPH_HOPS max_nodes=$SUBGRAPH_MAX_NODES max_edges=$SUBGRAPH_MAX_EDGES recursion=$SUBGRAPH_RECURSION_STEPS"
echo "[method] loss=bce_hardneg($SUBGRAPH_BCE_HARD_NEGATIVE_TOPK)+rank(w=$SUBGRAPH_RANKING_WEIGHT,m=$SUBGRAPH_RANKING_MARGIN,topk=$SUBGRAPH_HARD_NEGATIVE_TOPK)"
echo "[method] train_eval_split=$TRAIN_EVAL_SPLIT lr=$LR batch=$BATCH_SIZE epochs=$EPOCHS"

CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3}" \
NPROC_PER_NODE="$NPROC_PER_NODE" \
MASTER_PORT="$MASTER_PORT" \
DDP_TIMEOUT_MINUTES="$DDP_TIMEOUT_MINUTES" \
PYTORCH_CUDA_ALLOC_CONF="$PYTORCH_CUDA_ALLOC_CONF" \
WANDB_MODE="$WANDB_MODE" \
WANDB_PROJECT="$WANDB_PROJECT" \
DATASET="$DATASET" \
MODEL_IMPL="$MODEL_IMPL" \
EMB_MODEL="$EMB_MODEL" \
EMB_TAG="$EMB_TAG" \
EMB_DIR="$EMB_DIR" \
EPOCHS="$EPOCHS" \
BATCH_SIZE="$BATCH_SIZE" \
LR="$LR" \
EVAL_LIMIT="$EVAL_LIMIT" \
EVAL_EVERY_EPOCHS="$EVAL_EVERY_EPOCHS" \
EVAL_START_EPOCH="$EVAL_START_EPOCH" \
TRAIN_EVAL_SPLIT="$TRAIN_EVAL_SPLIT" \
AUTO_TEST_AFTER_TRAIN="$AUTO_TEST_AFTER_TRAIN" \
SUBGRAPH_HOPS="$SUBGRAPH_HOPS" \
SUBGRAPH_MAX_NODES="$SUBGRAPH_MAX_NODES" \
SUBGRAPH_MAX_EDGES="$SUBGRAPH_MAX_EDGES" \
SUBGRAPH_RECURSION_STEPS="$SUBGRAPH_RECURSION_STEPS" \
SUBGRAPH_DROPOUT="$SUBGRAPH_DROPOUT" \
SUBGRAPH_POS_WEIGHT_MODE="$SUBGRAPH_POS_WEIGHT_MODE" \
SUBGRAPH_POS_WEIGHT_MAX="$SUBGRAPH_POS_WEIGHT_MAX" \
SUBGRAPH_SPLIT_REVERSE_RELATIONS="$SUBGRAPH_SPLIT_REVERSE_RELATIONS" \
SUBGRAPH_DIRECTION_EMBEDDING_ENABLED="$SUBGRAPH_DIRECTION_EMBEDDING_ENABLED" \
SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED="$SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED" \
SUBGRAPH_BCE_HARD_NEGATIVE_TOPK="$SUBGRAPH_BCE_HARD_NEGATIVE_TOPK" \
SUBGRAPH_RANKING_ENABLED="$SUBGRAPH_RANKING_ENABLED" \
SUBGRAPH_RANKING_WEIGHT="$SUBGRAPH_RANKING_WEIGHT" \
SUBGRAPH_RANKING_MARGIN="$SUBGRAPH_RANKING_MARGIN" \
SUBGRAPH_HARD_NEGATIVE_TOPK="$SUBGRAPH_HARD_NEGATIVE_TOPK" \
SUBGRAPH_LR_SCHEDULER="$SUBGRAPH_LR_SCHEDULER" \
SUBGRAPH_LR_MIN="$SUBGRAPH_LR_MIN" \
bash trm_rag_style/scripts/run_train_subgraph_hardloss_resume.sh
