#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

# KGQA y/z outer-reasoning profile (kept separate from existing scripts).
DATASET="${DATASET:-cwq}"
MODEL_IMPL="${MODEL_IMPL:-trm_hier6}"
EMB_MODEL="${EMB_MODEL:-intfloat/multilingual-e5-large}"
EMB_TAG="${EMB_TAG:-e5_w4_g4}"
EMB_DIR="${EMB_DIR:-trm_agent/emb/${DATASET}_${EMB_TAG}}"

CKPT="${CKPT:-}"
CKPT_DIR="${CKPT_DIR:-trm_agent/ckpt/${DATASET}_${MODEL_IMPL}_subgraph_outer_yz}"
SUBGRAPH_RESUME_EPOCH="${SUBGRAPH_RESUME_EPOCH:-0}"
FROM_SCRATCH="${FROM_SCRATCH:-true}"

EPOCHS="${EPOCHS:-8}"
BATCH_SIZE="${BATCH_SIZE:-1}"
HIDDEN_SIZE="${HIDDEN_SIZE:-768}"
EVAL_LIMIT="${EVAL_LIMIT:--1}"
TRAIN_EVAL_SPLIT="${TRAIN_EVAL_SPLIT:-dev}"
AUTO_TEST_AFTER_TRAIN="${AUTO_TEST_AFTER_TRAIN:-true}"

SUBGRAPH_HOPS="${SUBGRAPH_HOPS:-3}"
SUBGRAPH_MAX_NODES="${SUBGRAPH_MAX_NODES:-2048}"
SUBGRAPH_MAX_EDGES="${SUBGRAPH_MAX_EDGES:-8192}"
SUBGRAPH_RECURSION_STEPS="${SUBGRAPH_RECURSION_STEPS:-16}"
SUBGRAPH_DROPOUT="${SUBGRAPH_DROPOUT:-0.1}"
SUBGRAPH_POS_WEIGHT_MODE="${SUBGRAPH_POS_WEIGHT_MODE:-auto}"
SUBGRAPH_POS_WEIGHT_MAX="${SUBGRAPH_POS_WEIGHT_MAX:-64}"
SUBGRAPH_SPLIT_REVERSE_RELATIONS="${SUBGRAPH_SPLIT_REVERSE_RELATIONS:-false}"
SUBGRAPH_DIRECTION_EMBEDDING_ENABLED="${SUBGRAPH_DIRECTION_EMBEDDING_ENABLED:-false}"

# Outer y/z loop
SUBGRAPH_OUTER_REASONING_ENABLED="${SUBGRAPH_OUTER_REASONING_ENABLED:-true}"
SUBGRAPH_OUTER_REASONING_STEPS="${SUBGRAPH_OUTER_REASONING_STEPS:-3}"

# Keep hardloss defaults from current setup.
SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED="${SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED:-true}"
SUBGRAPH_BCE_HARD_NEGATIVE_TOPK="${SUBGRAPH_BCE_HARD_NEGATIVE_TOPK:-64}"
SUBGRAPH_RANKING_ENABLED="${SUBGRAPH_RANKING_ENABLED:-true}"
SUBGRAPH_RANKING_WEIGHT="${SUBGRAPH_RANKING_WEIGHT:-0.1}"
SUBGRAPH_RANKING_MARGIN="${SUBGRAPH_RANKING_MARGIN:-0.5}"
SUBGRAPH_HARD_NEGATIVE_TOPK="${SUBGRAPH_HARD_NEGATIVE_TOPK:-16}"
SUBGRAPH_GRAD_ACCUM_STEPS="${SUBGRAPH_GRAD_ACCUM_STEPS:-1}"

# LR policy:
# - from scratch: cosine annealing (high -> low)
# - resume ft: constant LR by default
if [ "$FROM_SCRATCH" = "true" ]; then
  LR="${LR:-1.5e-5}"
  SUBGRAPH_LR_SCHEDULER="${SUBGRAPH_LR_SCHEDULER:-cosine}"
  SUBGRAPH_LR_MIN="${SUBGRAPH_LR_MIN:-1e-6}"
else
  LR="${LR:-1e-6}"
  SUBGRAPH_LR_SCHEDULER="${SUBGRAPH_LR_SCHEDULER:-none}"
  SUBGRAPH_LR_MIN="${SUBGRAPH_LR_MIN:-0.0}"
fi

WANDB_MODE="${WANDB_MODE:-online}"
WANDB_PROJECT="${WANDB_PROJECT:-graph-traverse}"
WANDB_RUN_NAME="${WANDB_RUN_NAME:-${DATASET}_outer_yz}"

echo "[outer-yz] enabled=$SUBGRAPH_OUTER_REASONING_ENABLED steps=$SUBGRAPH_OUTER_REASONING_STEPS"
echo "[outer-yz] from_scratch=$FROM_SCRATCH ckpt=${CKPT:-<none>} resume_ep=$SUBGRAPH_RESUME_EPOCH ckpt_dir=$CKPT_DIR"
echo "[outer-yz] train_eval_split=$TRAIN_EVAL_SPLIT lr=$LR batch=$BATCH_SIZE epochs=$EPOCHS hidden=$HIDDEN_SIZE grad_accum=$SUBGRAPH_GRAD_ACCUM_STEPS scheduler=$SUBGRAPH_LR_SCHEDULER lr_min=$SUBGRAPH_LR_MIN"

COMMON_ENV=(
  CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3}"
  NPROC_PER_NODE="${NPROC_PER_NODE:-4}"
  MASTER_PORT="${MASTER_PORT:-29618}"
  DDP_TIMEOUT_MINUTES="${DDP_TIMEOUT_MINUTES:-180}"
  PYTORCH_ALLOC_CONF="${PYTORCH_ALLOC_CONF:-expandable_segments:True}"
  PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
  DATASET="$DATASET"
  MODEL_IMPL="$MODEL_IMPL"
  EMB_MODEL="$EMB_MODEL"
  EMB_TAG="$EMB_TAG"
  EMB_DIR="$EMB_DIR"
  CKPT_DIR="$CKPT_DIR"
  EPOCHS="$EPOCHS"
  BATCH_SIZE="$BATCH_SIZE"
  LR="$LR"
  HIDDEN_SIZE="$HIDDEN_SIZE"
  EVAL_LIMIT="$EVAL_LIMIT"
  TRAIN_EVAL_SPLIT="$TRAIN_EVAL_SPLIT"
  AUTO_TEST_AFTER_TRAIN="$AUTO_TEST_AFTER_TRAIN"
  SUBGRAPH_HOPS="$SUBGRAPH_HOPS"
  SUBGRAPH_MAX_NODES="$SUBGRAPH_MAX_NODES"
  SUBGRAPH_MAX_EDGES="$SUBGRAPH_MAX_EDGES"
  SUBGRAPH_RECURSION_STEPS="$SUBGRAPH_RECURSION_STEPS"
  SUBGRAPH_DROPOUT="$SUBGRAPH_DROPOUT"
  SUBGRAPH_POS_WEIGHT_MODE="$SUBGRAPH_POS_WEIGHT_MODE"
  SUBGRAPH_POS_WEIGHT_MAX="$SUBGRAPH_POS_WEIGHT_MAX"
  SUBGRAPH_SPLIT_REVERSE_RELATIONS="$SUBGRAPH_SPLIT_REVERSE_RELATIONS"
  SUBGRAPH_DIRECTION_EMBEDDING_ENABLED="$SUBGRAPH_DIRECTION_EMBEDDING_ENABLED"
  SUBGRAPH_OUTER_REASONING_ENABLED="$SUBGRAPH_OUTER_REASONING_ENABLED"
  SUBGRAPH_OUTER_REASONING_STEPS="$SUBGRAPH_OUTER_REASONING_STEPS"
  SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED="$SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED"
  SUBGRAPH_BCE_HARD_NEGATIVE_TOPK="$SUBGRAPH_BCE_HARD_NEGATIVE_TOPK"
  SUBGRAPH_RANKING_ENABLED="$SUBGRAPH_RANKING_ENABLED"
  SUBGRAPH_RANKING_WEIGHT="$SUBGRAPH_RANKING_WEIGHT"
  SUBGRAPH_RANKING_MARGIN="$SUBGRAPH_RANKING_MARGIN"
  SUBGRAPH_HARD_NEGATIVE_TOPK="$SUBGRAPH_HARD_NEGATIVE_TOPK"
  SUBGRAPH_GRAD_ACCUM_STEPS="$SUBGRAPH_GRAD_ACCUM_STEPS"
  SUBGRAPH_LR_SCHEDULER="$SUBGRAPH_LR_SCHEDULER"
  SUBGRAPH_LR_MIN="$SUBGRAPH_LR_MIN"
  WANDB_MODE="$WANDB_MODE"
  WANDB_PROJECT="$WANDB_PROJECT"
  WANDB_RUN_NAME="$WANDB_RUN_NAME"
)

if [ "$FROM_SCRATCH" = "true" ]; then
  env "${COMMON_ENV[@]}" \
    CKPT="" \
    AUTO_RESUME=false \
    SUBGRAPH_RESUME_EPOCH=0 \
    bash trm_rag_style/scripts/run_train_subgraph_v2_resume.sh
else
  env "${COMMON_ENV[@]}" \
    CKPT="$CKPT" \
    SUBGRAPH_RESUME_EPOCH="$SUBGRAPH_RESUME_EPOCH" \
    SELECT_IF_MISSING=false \
    bash trm_rag_style/scripts/run_train_subgraph_hardloss_resume.sh
fi
