#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

# Load baseline snapshot first.
# shellcheck source=/dev/null
source "$REPO_ROOT/trm_rag_style/configs/subgraph_method_current_hardloss.env"

# Upgrade-v1 defaults (can be overridden via env).
UPGRADE_PROFILE="${UPGRADE_PROFILE:-hardloss_v1}"
UPGRADE_EPOCHS="${UPGRADE_EPOCHS:-6}"
UPGRADE_LR="${UPGRADE_LR:-5e-7}"
UPGRADE_EVAL_SPLIT="${UPGRADE_EVAL_SPLIT:-test}"
UPGRADE_BCE_TOPK="${UPGRADE_BCE_TOPK:-128}"
UPGRADE_RANK_TOPK="${UPGRADE_RANK_TOPK:-32}"
UPGRADE_RANK_WEIGHT="${UPGRADE_RANK_WEIGHT:-0.2}"
UPGRADE_RANK_MARGIN="${UPGRADE_RANK_MARGIN:-0.6}"
UPGRADE_POS_WEIGHT_MAX="${UPGRADE_POS_WEIGHT_MAX:-48}"
UPGRADE_SCHEDULER="${UPGRADE_SCHEDULER:-plateau}"
UPGRADE_PLATEAU_METRIC="${UPGRADE_PLATEAU_METRIC:-dev_hit1}"
UPGRADE_PLATEAU_FACTOR="${UPGRADE_PLATEAU_FACTOR:-0.5}"
UPGRADE_PLATEAU_PATIENCE="${UPGRADE_PLATEAU_PATIENCE:-1}"
UPGRADE_PLATEAU_THRESHOLD="${UPGRADE_PLATEAU_THRESHOLD:-0.0001}"

# Apply upgraded values.
EPOCHS="$UPGRADE_EPOCHS"
LR="$UPGRADE_LR"
TRAIN_EVAL_SPLIT="$UPGRADE_EVAL_SPLIT"
SUBGRAPH_BCE_HARD_NEGATIVE_TOPK="$UPGRADE_BCE_TOPK"
SUBGRAPH_HARD_NEGATIVE_TOPK="$UPGRADE_RANK_TOPK"
SUBGRAPH_RANKING_WEIGHT="$UPGRADE_RANK_WEIGHT"
SUBGRAPH_RANKING_MARGIN="$UPGRADE_RANK_MARGIN"
SUBGRAPH_POS_WEIGHT_MAX="$UPGRADE_POS_WEIGHT_MAX"
SUBGRAPH_LR_SCHEDULER="$UPGRADE_SCHEDULER"
SUBGRAPH_LR_PLATEAU_METRIC="$UPGRADE_PLATEAU_METRIC"
SUBGRAPH_LR_PLATEAU_FACTOR="$UPGRADE_PLATEAU_FACTOR"
SUBGRAPH_LR_PLATEAU_PATIENCE="$UPGRADE_PLATEAU_PATIENCE"
SUBGRAPH_LR_PLATEAU_THRESHOLD="$UPGRADE_PLATEAU_THRESHOLD"

# Keep outputs separated from baseline unless user explicitly sets CKPT_DIR.
if [ -z "${CKPT_DIR:-}" ]; then
  CKPT_DIR="trm_agent/ckpt/${DATASET}_${MODEL_IMPL}_subgraph_${UPGRADE_PROFILE}"
fi
if [ -z "${WANDB_RUN_NAME:-}" ]; then
  WANDB_RUN_NAME="${DATASET}_${UPGRADE_PROFILE}"
fi

echo "[method] upgrade_from=current_snapshot profile=$UPGRADE_PROFILE"
echo "[upgrade] lr=$LR epochs=$EPOCHS eval_split=$TRAIN_EVAL_SPLIT"
echo "[upgrade] bce_topk=$SUBGRAPH_BCE_HARD_NEGATIVE_TOPK rank_topk=$SUBGRAPH_HARD_NEGATIVE_TOPK rank_w=$SUBGRAPH_RANKING_WEIGHT margin=$SUBGRAPH_RANKING_MARGIN"
echo "[upgrade] scheduler=$SUBGRAPH_LR_SCHEDULER metric=$SUBGRAPH_LR_PLATEAU_METRIC factor=$SUBGRAPH_LR_PLATEAU_FACTOR patience=$SUBGRAPH_LR_PLATEAU_PATIENCE"
echo "[upgrade] ckpt_dir=$CKPT_DIR run_name=$WANDB_RUN_NAME"

CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3}" \
NPROC_PER_NODE="$NPROC_PER_NODE" \
MASTER_PORT="${MASTER_PORT:-29614}" \
DDP_TIMEOUT_MINUTES="$DDP_TIMEOUT_MINUTES" \
PYTORCH_CUDA_ALLOC_CONF="$PYTORCH_CUDA_ALLOC_CONF" \
WANDB_MODE="$WANDB_MODE" \
WANDB_PROJECT="$WANDB_PROJECT" \
WANDB_RUN_NAME="$WANDB_RUN_NAME" \
DATASET="$DATASET" \
MODEL_IMPL="$MODEL_IMPL" \
EMB_MODEL="$EMB_MODEL" \
EMB_TAG="$EMB_TAG" \
EMB_DIR="$EMB_DIR" \
CKPT_DIR="$CKPT_DIR" \
EPOCHS="$EPOCHS" \
BATCH_SIZE="$BATCH_SIZE" \
LR="$LR" \
EVAL_LIMIT="$EVAL_LIMIT" \
EVAL_EVERY_EPOCHS="$EVAL_EVERY_EPOCHS" \
EVAL_START_EPOCH="$EVAL_START_EPOCH" \
TRAIN_EVAL_SPLIT="$TRAIN_EVAL_SPLIT" \
AUTO_TEST_AFTER_TRAIN="$AUTO_TEST_AFTER_TRAIN" \
SUBGRAPH_HOPS="$SUBGRAPH_HOPS" \
SUBGRAPH_MAX_NODES="$SUBGRAPH_MAX_NODES" \
SUBGRAPH_MAX_EDGES="$SUBGRAPH_MAX_EDGES" \
SUBGRAPH_RECURSION_STEPS="$SUBGRAPH_RECURSION_STEPS" \
SUBGRAPH_DROPOUT="$SUBGRAPH_DROPOUT" \
SUBGRAPH_POS_WEIGHT_MODE="$SUBGRAPH_POS_WEIGHT_MODE" \
SUBGRAPH_POS_WEIGHT_MAX="$SUBGRAPH_POS_WEIGHT_MAX" \
SUBGRAPH_SPLIT_REVERSE_RELATIONS="$SUBGRAPH_SPLIT_REVERSE_RELATIONS" \
SUBGRAPH_DIRECTION_EMBEDDING_ENABLED="$SUBGRAPH_DIRECTION_EMBEDDING_ENABLED" \
SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED="$SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED" \
SUBGRAPH_BCE_HARD_NEGATIVE_TOPK="$SUBGRAPH_BCE_HARD_NEGATIVE_TOPK" \
SUBGRAPH_RANKING_ENABLED="$SUBGRAPH_RANKING_ENABLED" \
SUBGRAPH_RANKING_WEIGHT="$SUBGRAPH_RANKING_WEIGHT" \
SUBGRAPH_RANKING_MARGIN="$SUBGRAPH_RANKING_MARGIN" \
SUBGRAPH_HARD_NEGATIVE_TOPK="$SUBGRAPH_HARD_NEGATIVE_TOPK" \
SUBGRAPH_LR_SCHEDULER="$SUBGRAPH_LR_SCHEDULER" \
SUBGRAPH_LR_MIN="$SUBGRAPH_LR_MIN" \
SUBGRAPH_LR_PLATEAU_METRIC="$SUBGRAPH_LR_PLATEAU_METRIC" \
SUBGRAPH_LR_PLATEAU_FACTOR="$SUBGRAPH_LR_PLATEAU_FACTOR" \
SUBGRAPH_LR_PLATEAU_PATIENCE="$SUBGRAPH_LR_PLATEAU_PATIENCE" \
SUBGRAPH_LR_PLATEAU_THRESHOLD="$SUBGRAPH_LR_PLATEAU_THRESHOLD" \
bash trm_rag_style/scripts/run_train_subgraph_hardloss_resume.sh
