#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# shellcheck source=/dev/null
source "$REPO_ROOT/scripts/lib/portable_env.sh"
PYTHON_BIN="$(require_python_bin)"
cd "$REPO_ROOT"

DATASET="${DATASET:-cwq}"
MODEL_IMPL="${MODEL_IMPL:-trm_hier6}"
EMB_MODEL="${EMB_MODEL:-intfloat/multilingual-e5-large}"
EMB_TAG="${EMB_TAG:-$(echo "$EMB_MODEL" | tr '/:' '__' | tr -cd '[:alnum:]_.-')}"
EMB_DIR="${EMB_DIR:-trm_agent/emb/${DATASET}_${EMB_TAG}}"

SELECT_IF_MISSING="${SELECT_IF_MISSING:-true}"
EP_START="${EP_START:-20}"
EP_END="${EP_END:-28}"
REPORT_DIR_DEFAULT="logs/report_ep${EP_START}_${EP_END}"
BEST_ENV="${BEST_ENV:-${REPORT_DIR_DEFAULT}/best_ckpt.env}"
CKPT="${CKPT:-}"

if [ -z "$CKPT" ] && [ ! -f "$BEST_ENV" ] && [ "$SELECT_IF_MISSING" = "true" ]; then
  echo "[info] BEST_ENV not found: $BEST_ENV"
  echo "[info] run selector first (ep${EP_START}~ep${EP_END}) to create report/env"
  mkdir -p "$(dirname "$BEST_ENV")"
  DATASET="$DATASET" \
  MODEL_IMPL="$MODEL_IMPL" \
  EMB_MODEL="$EMB_MODEL" \
  EMB_TAG="$EMB_TAG" \
  EMB_DIR="$EMB_DIR" \
  CKPT_DIR="${CKPT_DIR:-trm_agent/ckpt/${DATASET}_${MODEL_IMPL}_subgraph_r16_h768_schedcos_scratch}" \
  EP_START="$EP_START" \
  EP_END="$EP_END" \
  EVAL_LIMIT="${EVAL_LIMIT:--1}" \
  BATCH_SIZE="${SELECT_BATCH_SIZE:-8}" \
  CUDA_DEVICE="${SELECT_CUDA_DEVICE:-0}" \
  OUT_DIR="$(dirname "$BEST_ENV")" \
  BEST_ENV="$BEST_ENV" \
  bash trm_rag_style/scripts/run_select_subgraph_ckpt_devtest_gap.sh
fi

if [ -z "$CKPT" ] && [ -f "$BEST_ENV" ]; then
  # shellcheck source=/dev/null
  source "$BEST_ENV"
  CKPT="${BEST_CKPT:-}"
fi
if [ -z "$CKPT" ]; then
  echo "[err] CKPT is empty. Set CKPT=... or create $BEST_ENV first."
  exit 2
fi
if [ ! -f "$CKPT" ]; then
  echo "[err] ckpt not found: $CKPT"
  exit 2
fi

infer_resume_epoch() {
  local ckpt_path="$1"
  local b
  b="$(basename "$ckpt_path")"
  if [[ "$b" =~ model_ep([0-9]+)\.pt$ ]]; then
    echo "${BASH_REMATCH[1]}"
  else
    echo "0"
  fi
}

# Match hidden/recursion from checkpoint by default to avoid shape mismatch.
AUTO_MATCH_MODEL_CFG="${AUTO_MATCH_MODEL_CFG:-true}"
if [ "$AUTO_MATCH_MODEL_CFG" = "true" ]; then
  cfg_vals="$("$PYTHON_BIN" - <<PY
import torch
obj=torch.load("$CKPT",map_location="cpu")
cfg=obj.get("model_cfg",{}) if isinstance(obj,dict) else {}
print(int(cfg.get("hidden_size",768)), int(cfg.get("recursion_steps",16)))
PY
)"
  CKPT_HIDDEN="$(echo "$cfg_vals" | awk '{print $1}')"
  CKPT_RECURSION="$(echo "$cfg_vals" | awk '{print $2}')"
else
  CKPT_HIDDEN="768"
  CKPT_RECURSION="16"
fi

HIDDEN_SIZE="${HIDDEN_SIZE:-$CKPT_HIDDEN}"
SUBGRAPH_RECURSION_STEPS="${SUBGRAPH_RECURSION_STEPS:-$CKPT_RECURSION}"
SUBGRAPH_RESUME_EPOCH="${SUBGRAPH_RESUME_EPOCH:-$(infer_resume_epoch "$CKPT")}"

# Resume+overwrite mode: keep same ckpt_dir unless overridden.
CKPT_DIR="${CKPT_DIR:-$(dirname "$CKPT")}"

# Conservative fine-tuning setup (constant LR + harder loss).
EPOCHS="${EPOCHS:-10}"
BATCH_SIZE="${BATCH_SIZE:-1}"
LR="${LR:-1e-6}"
EVAL_LIMIT="${EVAL_LIMIT:--1}"
EVAL_EVERY_EPOCHS="${EVAL_EVERY_EPOCHS:-1}"
EVAL_START_EPOCH="${EVAL_START_EPOCH:-1}"
TRAIN_EVAL_SPLIT="${TRAIN_EVAL_SPLIT:-dev}"  # dev|test
AUTO_TEST_AFTER_TRAIN="${AUTO_TEST_AFTER_TRAIN:-true}"

SUBGRAPH_HOPS="${SUBGRAPH_HOPS:-3}"
SUBGRAPH_MAX_NODES="${SUBGRAPH_MAX_NODES:-2048}"
SUBGRAPH_MAX_EDGES="${SUBGRAPH_MAX_EDGES:-8192}"
SUBGRAPH_DROPOUT="${SUBGRAPH_DROPOUT:-0.1}"
SUBGRAPH_POS_WEIGHT_MODE="${SUBGRAPH_POS_WEIGHT_MODE:-auto}"
SUBGRAPH_POS_WEIGHT_MAX="${SUBGRAPH_POS_WEIGHT_MAX:-64}"

SUBGRAPH_SPLIT_REVERSE_RELATIONS="${SUBGRAPH_SPLIT_REVERSE_RELATIONS:-false}"
SUBGRAPH_DIRECTION_EMBEDDING_ENABLED="${SUBGRAPH_DIRECTION_EMBEDDING_ENABLED:-false}"
SUBGRAPH_OUTER_REASONING_ENABLED="${SUBGRAPH_OUTER_REASONING_ENABLED:-false}"
SUBGRAPH_OUTER_REASONING_STEPS="${SUBGRAPH_OUTER_REASONING_STEPS:-3}"

SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED="${SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED:-true}"
SUBGRAPH_BCE_HARD_NEGATIVE_TOPK="${SUBGRAPH_BCE_HARD_NEGATIVE_TOPK:-64}"
SUBGRAPH_RANKING_ENABLED="${SUBGRAPH_RANKING_ENABLED:-true}"
SUBGRAPH_RANKING_WEIGHT="${SUBGRAPH_RANKING_WEIGHT:-0.1}"
SUBGRAPH_RANKING_MARGIN="${SUBGRAPH_RANKING_MARGIN:-0.5}"
SUBGRAPH_HARD_NEGATIVE_TOPK="${SUBGRAPH_HARD_NEGATIVE_TOPK:-16}"
SUBGRAPH_GRAD_ACCUM_STEPS="${SUBGRAPH_GRAD_ACCUM_STEPS:-1}"

# Constant LR.
SUBGRAPH_LR_SCHEDULER="${SUBGRAPH_LR_SCHEDULER:-none}"
SUBGRAPH_LR_MIN="${SUBGRAPH_LR_MIN:-0.0}"

WANDB_MODE="${WANDB_MODE:-online}"
WANDB_RUN_NAME="${WANDB_RUN_NAME:-${DATASET}_hardloss_resume_ep${SUBGRAPH_RESUME_EPOCH}}"

echo "[resume] ckpt=$CKPT"
echo "[resume] subgraph_resume_epoch=$SUBGRAPH_RESUME_EPOCH hidden_size=$HIDDEN_SIZE recursion=$SUBGRAPH_RECURSION_STEPS"
echo "[ft] lr=$LR scheduler=$SUBGRAPH_LR_SCHEDULER rank_weight=$SUBGRAPH_RANKING_WEIGHT rank_margin=$SUBGRAPH_RANKING_MARGIN bce_hardneg=$SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED grad_accum=$SUBGRAPH_GRAD_ACCUM_STEPS"

CKPT="$CKPT" \
SUBGRAPH_RESUME_EPOCH="$SUBGRAPH_RESUME_EPOCH" \
CKPT_DIR="$CKPT_DIR" \
EPOCHS="$EPOCHS" \
BATCH_SIZE="$BATCH_SIZE" \
LR="$LR" \
HIDDEN_SIZE="$HIDDEN_SIZE" \
EVAL_LIMIT="$EVAL_LIMIT" \
EVAL_EVERY_EPOCHS="$EVAL_EVERY_EPOCHS" \
EVAL_START_EPOCH="$EVAL_START_EPOCH" \
TRAIN_EVAL_SPLIT="$TRAIN_EVAL_SPLIT" \
AUTO_TEST_AFTER_TRAIN="$AUTO_TEST_AFTER_TRAIN" \
EMB_MODEL="$EMB_MODEL" \
EMB_TAG="$EMB_TAG" \
EMB_DIR="$EMB_DIR" \
DATASET="$DATASET" \
MODEL_IMPL="$MODEL_IMPL" \
WANDB_MODE="$WANDB_MODE" \
WANDB_RUN_NAME="$WANDB_RUN_NAME" \
SUBGRAPH_HOPS="$SUBGRAPH_HOPS" \
SUBGRAPH_MAX_NODES="$SUBGRAPH_MAX_NODES" \
SUBGRAPH_MAX_EDGES="$SUBGRAPH_MAX_EDGES" \
SUBGRAPH_RECURSION_STEPS="$SUBGRAPH_RECURSION_STEPS" \
SUBGRAPH_DROPOUT="$SUBGRAPH_DROPOUT" \
SUBGRAPH_POS_WEIGHT_MODE="$SUBGRAPH_POS_WEIGHT_MODE" \
SUBGRAPH_POS_WEIGHT_MAX="$SUBGRAPH_POS_WEIGHT_MAX" \
SUBGRAPH_SPLIT_REVERSE_RELATIONS="$SUBGRAPH_SPLIT_REVERSE_RELATIONS" \
SUBGRAPH_DIRECTION_EMBEDDING_ENABLED="$SUBGRAPH_DIRECTION_EMBEDDING_ENABLED" \
SUBGRAPH_OUTER_REASONING_ENABLED="$SUBGRAPH_OUTER_REASONING_ENABLED" \
SUBGRAPH_OUTER_REASONING_STEPS="$SUBGRAPH_OUTER_REASONING_STEPS" \
SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED="$SUBGRAPH_BCE_HARD_NEGATIVE_ENABLED" \
SUBGRAPH_BCE_HARD_NEGATIVE_TOPK="$SUBGRAPH_BCE_HARD_NEGATIVE_TOPK" \
SUBGRAPH_GRAD_ACCUM_STEPS="$SUBGRAPH_GRAD_ACCUM_STEPS" \
SUBGRAPH_RANKING_ENABLED="$SUBGRAPH_RANKING_ENABLED" \
SUBGRAPH_RANKING_WEIGHT="$SUBGRAPH_RANKING_WEIGHT" \
SUBGRAPH_RANKING_MARGIN="$SUBGRAPH_RANKING_MARGIN" \
SUBGRAPH_HARD_NEGATIVE_TOPK="$SUBGRAPH_HARD_NEGATIVE_TOPK" \
SUBGRAPH_LR_SCHEDULER="$SUBGRAPH_LR_SCHEDULER" \
SUBGRAPH_LR_MIN="$SUBGRAPH_LR_MIN" \
bash trm_rag_style/scripts/run_train_subgraph_v2_resume.sh
